### ISSUE TITLE
[BUG]: react-dom.development.js:86 Warning: ReactDOM.hydrate is no longer supported in React 18

### ISSUE THREAD

**Issue by MakFly** [BeerMoneyDev/nest-remix#1]
### Make sure these boxes are checked before submitting your issue, thank you!

- [X] You are using NodeJs 14 or higher?
- [X] You have installed all dependencies and tools listed in the documentation?
- [X] You have searched the existing issues if someone has already asked the same issue?
- [X] You have read the documentation?
- [X] Is not a programming question.
- [ ] You are using latest code of Starter?

### Description of the bug

Warning in url http://localhost:3000/hello-world

Display warning : 
react-dom.development.js:86 Warning: ReactDOM.hydrate is no longer supported in React 18

react-dom.development.js:86 Warning: Expected server HTML to contain a matching <script> in <body>.
    at script
    at LiveReload2 (http://localhost:3000/build/_shared/chunk-STNH4C2R.js:7443:3)
    at body
    at html
    at App
    at RemixRoute (http://localhost:3000/build/_shared/chunk-STNH4C2R.js:6863:3)
    at RenderedRoute (http://localhost:3000/build/_shared/chunk-STNH4C2R.js:4410:5)
    at RenderErrorBoundary (http://localhost:3000/build/_shared/chunk-STNH4C2R.js:4775:9)
    at Routes (http://localhost:3000/build/_shared/chunk-STNH4C2R.js:4648:5)
    at Router (http://localhost:3000/build/_shared/chunk-STNH4C2R.js:4595:15)
    at RouterProvider (http://localhost:3000/build/_shared/chunk-STNH4C2R.js:4546:5)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-STNH4C2R.js:6491:5)
    at RemixBrowser (http://localhost:3000/build/_shared/chunk-STNH4C2R.js:7793:55)

### Steps To Reproduce

I created a basic project with the nestjs cli:
- nest new nest-demo

Added the nest-remix package
Launch the project with the command : npm run start:dev

Bug warning on the url http://localhost:3000/hello-world

### Which version of the app are you using?

v1.0.0

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by KerryRitter** [comment]
Possibly related: https://github.com/remix-run/remix/issues/4822

**Comment by MakFly** [comment]
Of course, but i need to use the latest package react, can you update your package ? for test ?

**Comment by st2r** [comment]
> Of course, but i need to use the latest package react, can you update your package ? for test ?

It's an API update form react, and template file generated by nest-remix maybe outdated. You could modify the `entry.client.tsx` manully.

from 
```tsx
import { hydrate } from 'react-dom';

hydrate(<RemixBrowser />, document);
```

to
```tsx
import { createRoot } from 'react-dom/client';

const root = createRoot(document.documentElement);
root.render(<RemixBrowser/>)
```

**Comment by reallyely** [comment]
This worked for me, thanks @St2r

**Comment by KerryRitter** [comment]
Awesome. Thanks @st2r for finding the fix and @reallyely for confirming. I'll update this ASAP.

If you guys are using nest-remix, let me know how you are finding it :) I am hoping to get more time to work on it soon.

**Comment by reallyely** [comment]
I just watched your video last night. Today is trying to get a demo app working. I'm excited by what I see so far!

**Comment by st2r** [comment]
I also learned about it from youtube, remix.js and next.js and two of my favorite framework, it's very awesome to combine them! XD

**Comment by KerryRitter** [comment]
That's awesome! Same - I am eager to do more work with this project. I have a vision of turning this into a full-fledged framework powered by Nest and Remix
